WITH RECURSIVE ECOLI_TREE AS (
    # 최초의 대장균 개체
    SELECT ID, PARENT_ID, 1 GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    # 1세대 이후 
    SELECT ECOLI_DATA.ID, ECOLI_DATA.PARENT_ID, ECOLI_TREE.GENERATION + 1
    FROM ECOLI_DATA 
    JOIN ECOLI_TREE  
    ON ECOLI_DATA.PARENT_ID = ECOLI_TREE.ID
)

SELECT ID
FROM ECOLI_TREE
WHERE GENERATION = 3
ORDER BY ID