# USER_ID, PRODUCT_ID의 결과
SELECT USER_ID, PRODUCT_ID

# 테이블:ONLINE_SALE 
FROM ONLINE_SALE

# 중복되는 항목 조사를 할 컬럼
GROUP BY USER_ID,PRODUCT_ID

# 1개 이상 (갯수)
HAVING COUNT(PRODUCT_ID) > 1

# 회원 ID를 기준으로 오름차순 정렬
ORDER BY USER_ID, PRODUCT_ID DESC