SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE

# 조건 : 전화번호가 NULL인 경우는 출력대상에서 제외, 생일이 3월인 여성 회원
WHERE IFNULL(TLNO, null) AND DATE_OF_BIRTH LIKE '%-03-%' AND GENDER = 'W'

# 정렬 : 회원ID를 기준으로 오름차순
ORDER BY MEMBER_ID;