SELECT USED_GOODS_USER.USER_ID, USED_GOODS_USER.NICKNAME, SUM(USED_GOODS_BOARD.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD
JOIN USED_GOODS_USER
ON USED_GOODS_BOARD.WRITER_ID = USED_GOODS_USER.USER_ID

# 조건 : 판매상태 -> 완료 ('DONE')
WHERE STATUS = 'DONE'

# 그룹화 : USER_ID
GROUP BY USED_GOODS_USER.USER_ID

# 그룹화 조건 : 70만원 이상
HAVING TOTAL_SALES >= 700000

# 정렬 : 총거래금액을 기준으로 오름차순
ORDER BY TOTAL_SALES