SELECT it.ITEM_ID, ii.ITEM_NAME, ii.RARITY 

FROM ITEM_INFO AS ii 
JOIN ITEM_TREE AS it

# ON으로도 작성 가능!
WHERE ii.ITEM_ID = it.ITEM_ID

# 조건 : ITEM_TREE(테이블)에 PARENT_ITEM_ID(칼럼)로, ITEM_INFO(테이블)에 ITEM_ID(칼럼)와 비교.
AND it.PARENT_ITEM_ID IN (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE')

# 정렬 : ITEM_ID 내림차순
ORDER By it.ITEM_ID DESC
