SELECT CHILD .ID, CHILD .GENOTYPE, PARENT.GENOTYPE PARENT_GENOTYPE
FROM ECOLI_DATA AS CHILD 
JOIN ECOLI_DATA AS PARENT
WHERE CHILD .PARENT_ID = PARENT.ID
AND CHILD.GENOTYPE & PARENT.GENOTYPE = PARENT.GENOTYPE
ORDER BY CHILD .ID