SELECT BOARD.TITLE, BOARD.BOARD_ID, REPLY.REPLY_ID, REPLY.WRITER_ID, REPLY.CONTENTS, DATE_FORMAT(REPLY.CREATED_DATE , '%Y-%m-%d') AS CREATED_DATE 

FROM USED_GOODS_BOARD AS BOARD
JOIN USED_GOODS_REPLY AS REPLY

# 두 테이블이 결합하는 조건 (INNER JOIN) : BOARD_ID
ON BOARD.BOARD_ID = REPLY.BOARD_ID

# 조건 : 2022년 10월에 작성
WHERE BOARD.CREATED_DATE LIKE '2022-10%'

# 댓글 작성일, 게시글 제목 오름차순
ORDER BY REPLY.CREATED_DATE, BOARD.TITLE;