# 조건 :
# 1. 2022년 1월의 카테고리 별 도서 판매량을 합산
# 2. 카테고리(CATEGORY), 총 판매량(TOTAL_SALES) 리스트를 출력
# 3. 카테고리명을 기준으로 오름차순 정렬

SELECT CATEGORY, SUM(B.SALES) AS TOTAL_SALES
FROM BOOK AS A
JOIN BOOK_SALES AS B
ON A.BOOK_ID = B.BOOK_ID

WHERE B.SALES_DATE LIKE '2022-01%'
GROUP BY A.CATEGORY
ORDER BY A.CATEGORY ;